Full basic functionality

diff --git a/normcore b/normcore
--- a/normcore
+++ b/normcore
@@ -6,9 +6,49 @@
 #
 # Copyright (c) 2014, Aaron Greenberg
 
+BASENAME="normalize.css"
+CURL=`which curl`
+PATH="`pwd`";
+VERSION="latest"
+
 # Cause exit if a command fails.
 set -o errexit
-# Exit if script attempts to use undeclared variables.
-set -o nounset
 
-curl "http://necolas.github.io/normalize.css/latest/normalize.css"
+while :; do
+
+  if test -d "$1"; then
+    PATH="$1"
+  fi
+
+  case "$1" in
+    -s|--sass) BASENAME="_normalize.scss" ;;
+
+    -v|--version)
+      if test "$2"; then
+        VERSION="$2"
+        shift 2
+        continue
+      else
+        echo 'ERROR: Must specify a version number with -v' >&2
+        exit 1
+      fi
+      ;;
+    --version=?*) VERSION="${1#*=}" ;;
+    --version=)
+      echo 'ERROR: Must specify a version number with -v' >&2
+      exit 1
+      ;;
+
+    *) break
+  esac
+
+  shift
+done
+
+if ! test "${PATH}" = "*/"; then
+  PATH="${PATH}/"
+fi
+
+NORMALIZE_URL="http://necolas.github.io/normalize.css/${VERSION}/normalize.css"
+
+${CURL} -fsSL "${NORMALIZE_URL}" > ${PATH}${BASENAME}
